--- #YAML:1.0
name:                Tie-FS
version:             0.1.0
abstract:            Read and write files using a tied hash
license:             perl
author:              
    - Deven T. Corzine <deven@ties.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
